### ISSUE TITLE
页面跳转

### ISSUE THREAD

**Issue by peapodss** [tyzlmjj/mygithub-issues#1]
如果能仓库内跳转到另一个仓库，那就很不错了！

**Comment by tyzlmjj** [comment]
跳转到另一个仓库是什么意思？我没有理解！是fork的仓库吗？

**Comment by peapodss** [comment]
> 跳转到另一个仓库是什么意思？我没有理解！是fork的仓库吗？

比如一个仓库的readme.md 里面会有另一个仓库的链接地址，但是点击链接是通过浏览器打开的，而不是在应用内直接跳转到另一个仓库。

**Comment by tyzlmjj** [comment]
了解了！这个链接打开确实有必要，我会在后续版本添加

**Comment by tyzlmjj** [comment]
`2.0.3`版本已经添加了这个功能

**Comment by peapodss** [comment]
还是有没法直接跳转的地址，例如这个链接
https://github.com/dev-cafe/cmake-cookbook/blob/master/README.md
里面目录，虽然不是跳转到另一个仓库，但也是github开头的链接

**Comment by tyzlmjj** [comment]
文件类型的链接是不行的！这个类型太多了
