### ISSUE TITLE
在问题详情页，没有跳转到项目页的入口。

### ISSUE THREAD

**Issue by feng99** [tyzlmjj/mygithub-issues#10]
有时候提了一个issues，对方几天后才回复，
只看问题本身想不起来具体情况，我需要看代码，但是无法跳转到项目页。

**Comment by tyzlmjj** [comment]
这个我会考虑加上的！我也遇到这个问题了

**Comment by feng99** [comment]
好的  谢谢. 有新版本记得通知我
