### ISSUE TITLE
标星的项目页面，希望增加搜索功能。

### ISSUE THREAD

**Issue by feng99** [tyzlmjj/mygithub-issues#11]
标星的项目页面，希望增加搜索功能。

原因
我star了50个项目，偶尔需要查看某几个，
大概只记得项目名字，需要翻呀翻，一直翻，才能找到。

谢谢。

**Comment by tyzlmjj** [comment]
这个我一直在考虑，就是没找到合适的API

**Comment by agronet-test** [comment]
官方的API我都看过了，没有能实现这个搜索的，除非通过获取用户所有的star项目列表然后做本地搜索，这种方式太牵强了！我觉得你想快速找到项目，可以试试app里面的分类功能

**Comment by feng99** [comment]
> 官方的API我都看过了，没有能实现这个搜索的，除非通过获取用户所有的star项目列表然后做本地搜索，这种方式太牵强了！我觉得你想快速找到项目，可以试试app里面的分类功能

嗯嗯 我现在使用的是 全局搜索功能  只要项目名字记得准  是能够搜索到的   
感谢2位的回复
