### ISSUE TITLE
无法提交issues 请看报错信息

### ISSUE THREAD

**Issue by feng99** [tyzlmjj/mygithub-issues#12]
![image](https://user-images.githubusercontent.com/13182572/83394888-f76ebc80-a42b-11ea-91ac-4673b23ddaed.png)

**Comment by feng99** [comment]
不止一个项目遇到这个问题，不过网页版的github可以提交

**Comment by tyzlmjj** [comment]
是API的权限限制了，V4版本的API限制了很多对组织的访问。有问题的项目应该都属于某个组织。我到时候再试下旧的API能不能用！

**Comment by feng99** [comment]
有问题的项目应该都属于某个组织
的确是这样.
