### ISSUE TITLE
Readme里的图片无法显示

### ISSUE THREAD

**Issue by feng99** [tyzlmjj/mygithub-issues#13]
图片都看不见。
需要翻越长城？

**Comment by tyzlmjj** [comment]
图片好像都是亚马逊的服务器，时好时坏，国内还是网络上的问题，很难解决。

**Comment by feng99** [comment]
> 图片好像都是亚马逊的服务器，时好时坏，国内还是网络上的问题，很难解决。

好的  了解了    祝端午节快乐哦ヾ(･ω･`｡)
