### ISSUE TITLE
网络不稳定

### ISSUE THREAD

**Issue by hainanss** [tyzlmjj/mygithub-issues#14]

**Comment by hainanss** [comment]
github  api 老是出问题

**Comment by tyzlmjj** [comment]
能具体点说下是哪里的问题吗？ 然后你现在使用的APP版本是多少？

**Comment by hainanss** [comment]
2.0.3版本    老是出现failed to execute http call------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;家杰&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年6月29日(星期一) 上午9:26
收件人:&nbsp;&quot;tyzlmjj/mygithub-issues&quot;<mygithub-issues@noreply.github.com&gt;;
抄送:&nbsp;&quot;hainanss&quot;<1126299738@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题:&nbsp;Re: [tyzlmjj/mygithub-issues] 网络不稳定 (#14)

**Comment by tyzlmjj** [comment]
建议更新到2.0.5。 如果是华为手机可能应用商店没有了。可以到这里下载https://github.com/tyzlmjj/mygithub-issues/releases
