### ISSUE TITLE
highlighting

### ISSUE THREAD

**Issue by pflegende** [tyzlmjj/mygithub-issues#18]
https://github.com/pflegende/BetteninventurTH/blob/master/BetteninventurThurTag3.ipynb

this is the file of a working jupyter- notebook, where highlighting doesn't functional

keep healthy

CU

**Comment by tyzlmjj** [comment]
I didn't find a tool to convert the jupyter format in Java or JS. There is only one [tool](https://github.com/jupyter/nbconvert) written in Python, which can't be used on Android platform!

**Comment by tyzlmjj** [comment]
[Version 2.0.7](https://github.com/tyzlmjj/mygithub-issues/releases) is already supported
