### ISSUE TITLE
项目分类数量限制

### ISSUE THREAD

**Issue by peapodss** [tyzlmjj/mygithub-issues#2]
最多只有20个分类，还能再多吗？

**Comment by tyzlmjj** [comment]
目前我不觉得个人需要这么多分类。我希望每一个项目的收藏都具有价值。假如只是随意记录项目，然后可能再也不会回顾这个项目的时候，可以选择star。

**Comment by peapodss** [comment]
然后又触发了收藏夹上限200条的限制，因为基本我star的仓库都会分类便于后面查找。
所以希望提高或者取消收藏分类20条以及收藏夹数量200条的限制

**Comment by tyzlmjj** [comment]
这个我过段时间调整下吧！这个月真的忙

**Comment by peapodss** [comment]
新版本还是有收藏数量的限制

**Comment by tyzlmjj** [comment]
这个我需要改后台API的，还没有修改，这周应该没时间修改了，要下周了！

**Comment by tyzlmjj** [comment]
已经提高了收藏上限
