### ISSUE TITLE
手机使用问题

### ISSUE THREAD

**Issue by coderjzh** [tyzlmjj/mygithub-issues#24]
HTTP 451如何解决

**Comment by tyzlmjj** [comment]
第三方的API问题！我要更换一个API了

**Comment by Fe1H** [comment]
Trending API 一直451噢

**Comment by tyzlmjj** [comment]
可以更新到[2.0.7版本](https://github.com/tyzlmjj/mygithub-issues/releases)，已经解决了问题。
