### ISSUE TITLE
查看文件卡顿

### ISSUE THREAD

**Issue by Leozhi-nian** [tyzlmjj/mygithub-issues#34]
文件打开时会卡住几秒钟，导致页面无法滑动，当开启显示行号时，打开文件会卡住直至无响应。

**Comment by tyzlmjj** [comment]
文件过大的话解析过程可能会比较慢。可以提供下文件地址，我测试下

**Comment by Leozhi-nian** [comment]
https://github.com/zyj1609wz/FileManager/blob/master/app/src/main/java/com/zyj/filemanager/MainActivity.java
