### ISSUE TITLE
修改用户名后出现的问题

### ISSUE THREAD

**Issue by tress101** [tyzlmjj/mygithub-issues#4]
修改用户名后，获取不到仓库信息

**Comment by tress101** [comment]
自己的仓库获取不到了，

**Comment by tyzlmjj** [comment]
确实存在这个问题！应用中使用的用户名在登陆之后被固定了，我会在后续版本修复这个问题。
临时的解决办法是你退出登录，重新再登录下就可以了！

**Comment by tress101** [comment]
重新推出登陆；卸载重新下载登陆，用手机分身安装登陆；这三种办法都是一样的效果，不能获取自己的项目提示的是能获取“旧名称”的仓库，。就差重新换个手机登陆了，O(∩_∩)O哈哈~

**Comment by tress101** [comment]
发现一个解决办法。在页面“我”--问题集--‘随便一个问题’---点击‘自己的头像’---点击‘项目’。就可以查看了。app很好用，希望一直维护更新

**Comment by tress101** [comment]
非常感谢您的积极回应，与对github的贡献！

**Comment by tyzlmjj** [comment]
2.0.5版本已经解决了这个问题。你可以在这个地址下载 https://github.com/tyzlmjj/mygithub-issues/releases
