### ISSUE TITLE
现在gethubAPI全用不了。

### ISSUE THREAD

**Issue by xoipz** [tyzlmjj/mygithub-issues#43]
API状态显示GitHub API 两个都是Conection reset

**Comment by tyzlmjj** [comment]
APP版本号是多少？你所在城市是哪里？现在还不能用吗？

**Comment by xoipz** [comment]
APP版本号：2.0.10 ，github Api V3，GrpahQL API V4 ，城市：贵州贵阳 ， 现在还不能用

**Comment by tyzlmjj** [comment]
应该是网络问题！
可以看一下 https://api.github.com 是否可以打开

**Comment by xoipz** [comment]
确实不能打开

**Comment by talebolano** [comment]
湖南长沙也不能打开，怀疑是移动网络的问题，因为电信可以打开

**Comment by xoipz** [comment]
突然又能用了。。。

**Comment by xoipz** [comment]
现在关闭
