### ISSUE TITLE
不支持ts文件预览

### ISSUE THREAD

**Issue by cizkey** [tyzlmjj/mygithub-issues#5]
您好，app做的很好，是用过最舒服的。
发现一点小小的问题，typescript的项目，以ts为扩展名的源码不能直接查看。提示为不支持的文件类型，使用右上角的浏览器打开则被识别为了视频文件，希望能修复下这个问题。为盼！

**Comment by tyzlmjj** [comment]
可以发一下项目地址吗？我好排查

**Comment by tyzlmjj** [comment]
2.0.5版本已经解决了这个问题。你可以在这个地址下载 https://github.com/tyzlmjj/mygithub-issues/releases
