### ISSUE TITLE
打开源码文件显示不全

### ISSUE THREAD

**Issue by peapodss** [tyzlmjj/mygithub-issues#6]
打开部分C源码（如果源码文件较长）会只显示一部分，另一部分上下滑动也不会再显示了。
-by huawei p20

**Comment by tyzlmjj** [comment]
有文件的链接可以发一下吗？

**Comment by peapodss** [comment]
https://github.com/embedded-software-laboratory/embeddedRTPS-STM32/blob/master/stm32/Src/ethernetif.c

FYI

**Comment by tyzlmjj** [comment]
我测试了下，显示的是733行没有少的呀！
也许跟你使用的样式有关，你可以截图发一下吗？

**Comment by peapodss** [comment]
http://note.youdao.com/noteshare?id=8e8c27f7e15d39d6afceaa0d712550f5

有时候会直接卡住，没法上下滑动

**Comment by tyzlmjj** [comment]
我换成了你一样的样式，两台手机都没测出来！你手机是什么型号的呢？

**Comment by peapodss** [comment]
华为 P20
