### ISSUE TITLE
项目收藏到分类后，页面卡住。

### ISSUE THREAD

**Issue by feng99** [tyzlmjj/mygithub-issues#7]
项目收藏到分类后，提示成功，然后点击任何地方，都挺久在这个界面，用全面屏手势返回上一页也不行，
只能强制退出进程，再重新打开app
手机是小米8
每收藏支持都得这样操作，很痛苦。请修复，谢谢。

**Comment by feng99** [comment]
这里无法添加图片？？不知道你那里能否复现这个问题。

**Comment by feng99** [comment]
另外，这个功能start分类功能是这个app独有的吗？还是github自带的？感觉很实用呀。

**Comment by tyzlmjj** [comment]
这个分类的功能是我单独加的，GitHub本身是没有的。现在在外面，你说的这个问题我明天再测试下看看吧。目前我自己还没遇到过。
问下你的系统是什么版本的？

**Comment by feng99** [comment]
> 这个分类的功能是我单独加的，GitHub本身是没有的。现在在外面，你说的这个问题我明天再测试下看看吧。目前我自己还没遇到过。
> 问下你的系统是什么版本的？

小米手机8
MIUI11.0.6
安卓版本10

**Comment by feng99** [comment]
这个问题，还是这样。😂😂
我star了70个项目，的确想分类一下。
甚至想单独修改下项目的备注。

**Comment by feng99** [comment]
留个邮箱，我录个视频，你看一眼就了解具体的现象了。

**Comment by tyzlmjj** [comment]
tyzl931019@gmail.com

**Comment by feng99** [comment]
以发送到邮箱   视频在附件中

**Comment by tyzlmjj** [comment]
<img width="400" alt="开发者选项" src="https://user-images.githubusercontent.com/10722815/81770783-d6453b00-9513-11ea-81c0-6daf1fb35b74.png">

你是不是修改过开发者选项？开发者选项里面，我截图的这个动画时长不要关闭就可以解决你的问题了

**Comment by feng99** [comment]
> 改过开发者选项？开发者选项里面，我截图的这个动画时长不要关闭

还真是.   不过我没有设置过    不知道为何是关闭的

问题已解决  感谢作者的耐心回复.
