### ISSUE TITLE
可以把搜索功能做强大一点吗？

### ISSUE THREAD

**Issue by awerdx520** [tyzlmjj/mygithub-issues#9]
搜索功能可以像github一样根据语言，topic等等搜索。搜索readme内容也搜索到

**Comment by tyzlmjj** [comment]
语言的筛选条件我后续可能会加，但是像搜索文件不一定会加上，因为我用的GitHub API_V4没这些功能。然后V3的数据有点乱，开发起来很累！

**Comment by awerdx520** [comment]
ok, 感谢你提供的好用的工具，如果能添加就添加，不能添加就不用，现在功能基本可用，我也是搞开发的，非常理解。
